spin_manifest_version = 2

[application]
name = "pdf-test"
version = "0.1.0"
authors = ["Migsar Navarro <dev@migsar.com>"]
description = ""

[variables]
s3_endpoint = { required = true }
s3_key_id = { required = true }
s3_secret = { required = true }

# [[trigger.http]]
# route = "/static/..."
# component = "pdf-test"

# [component.pdf-test]
# source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
# files = [{ source = "./dist", destination = "/" }]

[[trigger.http]]
route = "/api"
component = "api"

[component.api]
source = "api/target/api.wasm"
exclude_files = ["**/node_modules"]
allowed_outbound_hosts = [
  "https://webhook.site",
  # "{{ s3_endpoint }}",
  "https://s3.us-east-005.backblazeb2.com",
]
[component.api.build]
command = "npm run build"
workdir = "api"
watch = ["src/**/*.ts", "package.json"]
[component.api.variables]
endpoint = "{{ s3_endpoint }}"
key_id = "{{ s3_key_id }}"
secret = "{{ s3_secret }}"
